#!/usr/bin/env bash

if [[ -z ${SITE_NAME} ]]; then
    echo "SITE_NAME must be set"
    exit 1
fi

echo "Updating ${SITE_NAME}.test"

if [[ -n ${NO_SYNC} ]]; then
  terminus env:deploy ${SITE_NAME}.test --updatedb --note="Deploy core and contrib updates"
else
  terminus env:deploy ${SITE_NAME}.test --sync-content --updatedb --note="Deploy core and contrib updates, update content from LIVE"
fi

CURRENT_UPSTREAM=$(terminus site:info ${SITE_NAME} --field upstream | sed 's/:.*$//g')
if [[ "${CURRENT_UPSTREAM}" == "3162cc4c-2f75-40cb-8487-0c69bda99f39" ]]; then
  terminus drush ${SITE_NAME}.test -- -n -y state:set config_sync.update_mode 1 --input-format=integer
  terminus drush ${SITE_NAME}.test -- -n -y config-distro-update
  terminus drush ${SITE_NAME}.test -- -n -y az-core-config-add-permissions
fi

terminus env:clear-cache ${SITE_NAME}.test

