#!/usr/bin/env bash

#
# Create new pantheon site
#
# Defaults:
#  - org: UA Campus Web Services
#  - region: United States
#  - upstream: Arizona Quickstart 2 
#

if [[ -z ${SITE_NAME} ]]; then
    echo "SITE_NAME must be set"
    exit 1
fi

if [[ -z ${SITE_LABEL} ]]; then
    SITE_LABEL=${SITE_NAME}
fi 

if [[ -z ${REGION} ]]; then
    REGION="us"
fi 

if [[ -z ${ORG} ]]; then
    ORG="ua-campus-web-services"
fi 

if [[ -z ${UPSTREAM} ]]; then
    UPSTREAM="3162cc4c-2f75-40cb-8487-0c69bda99f39"
fi 

echo "Creating ${SITE_NAME}.dev"

terminus site:create \
  --region=${REGION} \
  --org=${ORG} \
  ${SITE_NAME} \
  ${SITE_LABEL} \
  ${UPSTREAM}

